#%RAML 1.0 Trait
 headers:
        x-cms-transactionId:
          type: string
          required: true
          minLength: 26
          maxLength: 30
          example: "ABCDEF-12345-LMNOP-QRSTU-8WXYZ"
        clientID:
          type: string
          required: true
          example: "QWEDEF-12345-LMNOP-QRSTU-8WSSS"  
        clientSecret:
          type: string
          required: true
          example: "XYCDEF-12345-LMNOP-QRSTU-8WXAB"     