#%RAML 1.0 DataType
type: object
properties:
  msg:
    description: Thos feild will contain error message
    type: string
    required: true
    example: "successful operation"
  code:
    description: This feild will contain error response code
    type: integer
    required: true
    example: 400    
  success:
    description: Thos code will contain response code success
    type: boolean
    required: true
    example: true
  eventId:
    description: This feild will contain transaction Unique ID
    type: string
    required: true
    example: "suceess operation"
  error:
    description: This object will contain error reponse code
    type: object
    properties:
      type:
        description: This feild will contain error type
        type: string
        required: true
        example: "Mem101"            
      title:
        description: this feild will contaon error title
        type: string
        required: true
        example: "success"
      details:
        description: this feild will contaon error description
        type: string
        required: true
        example: "success"