#%RAML 1.0 DataType
type: object
properties:
  registrationRequest:
    type: object
    properties:
      contactType:
        type: string
        required: true
        enum:
          - mobile
          - email
      countryCode:
        type: string
        required: true
        enum:
          - "+91"
          - "+1"
      mobile:
        type: string
        required: false
        example: "9999999999"                    
      email:
        type: string
        required: false
        example: "abc@gmail.com"
      password:
        type: string
        required: true
        example: "password"

      acceptDataPolicy:
        type: boolean
        required: true
        example: true  
      receiveNews:
        type: boolean
        required: true
        example: true 
      acceptPIC:
        type: boolean
        required: true
        example: true 
      locale:
        type: string
        required: true
        enum:
          - en
          - tl
        example: en
      captchaToken:
          type: string
          required: true
          example: "ZBCDEF-12345-LMNOP-QRSTU-8WXYA"  
      receiveClaimSettle:
        type: boolean
        required: true
        example: true
